pandas 는 고수준의 자료 구조와 파이썬을 통한 빠르고 쉬운 데이터 분석 도구를 포함한다.

특징
* 범용성
* 유연성 & 간결성
* 시계열&비시계열 통합 자료구조

pandas import 컨벤션

In [2]:
from pandas import Series, DataFrame
import pandas as pd
import numpy as np

## 5.1. pandas 자료 구조 소개

### 5.1.1. Series

Series 란?<br/>일련의 객체를 담을 수 있는 1차원 배열 같은 자료 구조

In [2]:
obj = Series([4, 7, -5, 3])

In [3]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [5]:
obj.values

array([ 4,  7, -5,  3])

In [6]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
obj2 = Series([4, 7, -5, 3], index = ['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [8]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [9]:
obj2['a']

-5

In [10]:
obj2['d'] = 6

In [11]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [12]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [13]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [14]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [15]:
'b' in obj2

True

In [16]:
'e' in obj2

False

In [17]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [18]:
obj3 = Series(sdata)

In [19]:
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [20]:
states = ['Califonia', 'Ohio', 'Oregon', 'Texas']

In [21]:
obj4 = Series(sdata, index = states)

In [22]:
obj4

Califonia        NaN
Ohio         35000.0
Oregon       16000.0
Texas        71000.0
dtype: float64

In [23]:
pd.isnull(obj4)

Califonia     True
Ohio         False
Oregon       False
Texas        False
dtype: bool

In [24]:
pd.notnull(obj4)

Califonia    False
Ohio          True
Oregon        True
Texas         True
dtype: bool

In [25]:
obj4.isnull()

Califonia     True
Ohio         False
Oregon       False
Texas        False
dtype: bool

In [26]:
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [27]:
obj4

Califonia        NaN
Ohio         35000.0
Oregon       16000.0
Texas        71000.0
dtype: float64

In [28]:
obj3 + obj4

Califonia         NaN
Ohio          70000.0
Oregon        32000.0
Texas        142000.0
Utah              NaN
dtype: float64

In [29]:
obj4.name = 'population'

In [30]:
obj4.index.name = 'state'

In [31]:
obj4

state
Califonia        NaN
Ohio         35000.0
Oregon       16000.0
Texas        71000.0
Name: population, dtype: float64

In [32]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [33]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

### 5.1.2. DataFrame

DataFrame 은 표 같은 스프레드시트 형식의 자료 구조이다.
* 각 컬럼은 서로 다른 종류의 데이터(숫자, 문자열, 불리언 등) 를 담을 수 있다.
* 로우와 컬럼에 대한 색인이 존재한다.
* Series 객체를 담고 있는 파이썬의 Dictionary 로 생각할 수 있다.
* 내부적으로 2차원 형식으로 데이터를 저장

DataFrame 객체 생성방법

* 같은 길이의 리스트에 담긴 사전을 이용
* NumPy 배열을 이용

In [4]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'], 'year': [2000, 2001, 2002, 2001, 2002], 'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}
frame = DataFrame(data)

In [5]:
frame

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [6]:
DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [7]:
frame2 = DataFrame(data, columns=['year', 'state', 'pop', 'debt'], index=['one', 'two', 'three', 'four', 'five'])

In [8]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [9]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [10]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [11]:
frame2.ix['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [12]:
frame2['debt'] = 16.5

In [13]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

In [14]:
frame2['debt'] = np.arange(5.)

In [15]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0

리스트나 배열을 컬럼에 대입할 때는 대입하려는 값의 길이가 DataFrame 의 크기와 같아야 한다

In [17]:
val = Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

In [18]:
frame2['debt'] = val

In [19]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

존재하지 않는 컬럼에 데이터를 대입하면 컬럼이 생성된다.<br/>
파이썬 사전형에서와 마찬가지로 del 을 이용하여 컬럼을 삭제할 수 있다.

In [20]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt eastern
one    2000    Ohio  1.5   NaN    True
two    2001    Ohio  1.7  -1.2    True
three  2002    Ohio  3.6   NaN    True
four   2001  Nevada  2.4  -1.5   False
five   2002  Nevada  2.9  -1.7   False

In [21]:
frame2.columns

Index(['year', 'state', 'pop', 'debt', 'eastern'], dtype='object')

In [22]:
pop = {'Nevada': {2001:2.4, 2002:2.9},
      'Ohio': {2000:1.5, 2001:1.7, 2002:3.6}}

In [23]:
frame3 = DataFrame(pop)
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [25]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [26]:
DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [27]:
pdata = {'Ohio' : frame3['Ohio'][:-1],
        'Nevada': frame3['Nevada'][:2]}

In [28]:
DataFrame(pdata)

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7

In [29]:
frame3.index.name = 'year'
frame3.columns.name = 'state'

In [30]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [31]:
frame3.values

array([[ nan,  1.5],
       [ 2.4,  1.7],
       [ 2.9,  3.6]])

In [32]:
frame2.values

array([[2000, 'Ohio', 1.5, nan, True],
       [2001, 'Ohio', 1.7, -1.2, True],
       [2002, 'Ohio', 3.6, nan, True],
       [2001, 'Nevada', 2.4, -1.5, False],
       [2002, 'Nevada', 2.9, -1.7, False]], dtype=object)

DataFrame 생성자에서 사용 가능한 입력 데이터

<table align="left">
    <thead>
        <td>형</td>
        <td>설명</td>
    </thead>
    <tbody>
        <tr>
            <td>2차원 ndarray</td>
            <td>데이터를 담고 잇는 행렬, 선택적으로 로우와 컬럼의 이름을 전달할 수 있다.</td>
        </tr>
        <tr>
            <td>배열, 리스트, 튜플의 사전</td>
            <td>사전의 모든 항목은 같은 길이를 가져야 하며, 각 항목의 내용이 DataFrame 의 컬럼이 된다.</td>
        </tr>
        <tr>
            <td>NumPy의 구조화 배열</td>
            <td>배열의 사전과 같은 방식으로 취급된다.</td>
        </tr>
        <tr>
            <td>Series 사전</td>
            <td>Series의 각 값이 컬럼이 된다. 명시적으로 색인을 넘겨주지 않으면 Series의 색인이 하나로 합쳐져서 로우의 색인이 된다.</td>
        </tr>
        <tr>
            <td>사전의 사전</td>
            <td>내부에 있는 사전이 컬럼이 된다. 키 값은 'Series의 사전'과 마찬가지로 합쳐져 로우의 색인이 된다.</td>
        </tr>
        <tr>
            <td>사전이나 Series의 리스트</td>
            <td>리스트의 각 항목이 DataFrame의 로우가 된다. 합쳐진 사전의 키값이나 Series의 색인이 DataFrame 컬럼의 이름이 된다.</td>
        </tr>
        <tr>
            <td>리스트나 튜플의 리스트</td>
            <td>'2차원 ndarray'와 같은 방식으로 취급된다.</td>
        </tr>
        <tr>
            <td>다른 DataFrame</td>
            <td>색인이 따로 지정되지 않는다면 DataFrame의 색인이 그대로 사용된다.</td>
        </tr>
        <tr>
            <td>NumPy MaskedArray</td>
            <td>'2차원 ndarray'와 같은 방식으로 취급되지만 마스크 값은 반환되는 DataFrame에서 NA 값이 된다.</td>
        </tr>
    </tbody>
</table>

### 5.1.3. 색인 객체

pandas 의 색인 객체는 표 형식의 데이터에서 각 로우와 컬럼에 대한 이름과 다른 메타데이터(축의 이름 등)를 저장하는 객체이다.<br/>
Series 나 DataFrame 객체를 생성할 때 사용되는 배열이나 혹은 다른 순차적인 이름은 내부적으로 색인으로 변환된다.

In [33]:
obj = Series(range(3), index=['a', 'b', 'c'])

In [34]:
index = obj.index

In [35]:
index

Index(['a', 'b', 'c'], dtype='object')

In [36]:
index[1:]

Index(['b', 'c'], dtype='object')

색인은 변경 불가. 그래서 자료 구조 사이에서 안전하게 공유될 수 있다.

In [37]:
index[1] = 'd'

TypeError: Index does not support mutable operations

In [38]:
index = pd.Index(np.arange(3))

In [39]:
obj2 = Series([1.5, -2.5, 0], index=index)

In [40]:
obj2.index is index

True

pandas 의 주요 Index 객체

<table align="left">
    <thead>
        <td>클래스</td>
        <td>설명</td>
    </thead>
    <tbody>
        <tr>
            <td>Index</td>
            <td>가장 일반적인 Index 객체이며, 파있너 객체의 NumPy 배열 형식으로 축의 이름을 표현한다</td>
        </tr>
        <tr>
            <td>Int64Index</td>
            <td>정수 값을 위한 특수한 Index</td>
        </tr>
        <tr>
            <td>MultiIndex</td>
            <td>단일 축에 여러 단계의 색인을 표현하는 계층적 색인 객체, 튜플의 배열과 유사하다고 볼 수 있다.</td>
        </tr>
        <tr>
            <td>DatetimeIndex</td>
            <td>나노초 타임스탬프를 저장한다(NumPy 의 datatiem64 dtype 으로 표현한다)</td>
        </tr>
        <tr>
            <td>PeriodIndex</td>
            <td>기간 데이터를 위한 특수한 Index</td>
        </tr>
    </tbody>
</table>

In [41]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [42]:
'Ohio' in frame3.columns

True

In [43]:
2003 in frame3.index

False

색인 메서드와 속성

<table align="left">
    <thead>
        <td>메서드</td>
        <td>설명</td>
    </thead>
    <tbody>
        <tr>
            <td>append</td>
            <td>추가적인 Index 객체를 덧붙여 새로운 색인을 반환한다.</td>
        </tr>
        <tr>
            <td>diff</td>
            <td>색인의 차집합을 반환한다.</td>
        </tr>
        <tr>
            <td>intersection</td>
            <td>색인의 교집합을 반환한다.</td>
        </tr>
        <tr>
            <td>union</td>
            <td>색인의 합집합을 반환한다.</td>
        </tr>
        <tr>
            <td>isin</td>
            <td>넘겨받은 값이 해당 색인 위치에 존재하는지 알려주는 불리언 배열을 반환한다.</td>
        </tr>
        <tr>
            <td>delete</td>
            <td>i 위치의 색인이 삭제된 새로운 색인을 반환한다.</td>
        </tr>
        <tr>
            <td>drop</td>
            <td>넘겨받은 값이 삭제된 새로운 색인을 반환한다.</td>
        </tr>
        <tr>
            <td>insert</td>
            <td>i 위치에 값이 추가된 새로운 색인을 반환한다.</td>
        </tr>
        <tr>
            <td>is_monotonic</td>
            <td>색인이 단조성을 가진다면 True를 반한환다.</td>
        </tr>
        <tr>
            <td>is_unique</td>
            <td>중복되는 색인이 없다면 True를 반환한다.</td>
        </tr>
        <tr>
            <td>unique</td>
            <td>색인에서 중복되는 요소를 제거하고 유일한 값만을 반환한다.</td>
        </tr>
    </tbody>
</table>

* 단조성 - 진행방향이 항상 일정한 성질
    * 단조증가 - 항상 증가
    * 단조감소 - 항상 감소

## 5.2. 핵심기능

### 5.2.1. 재색인

In [46]:
obj = Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [47]:
obj2 = obj.reindex(['a', 'b', 'c' , 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [48]:
obj.reindex(['a', 'b', 'c', 'd', 'e'], fill_value=0)

a   -5.3
b    7.2
c    3.6
d    4.5
e    0.0
dtype: float64

In [49]:
obj3 = Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [50]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

reindex 메서드(보간) 옵션

<table align="left">
    <thead>
        <td>인자</td>
        <td>설명</td>
    </thead>
    <tbody>
        <tr>
            <td>ffill 또는 pad</td>
            <td>앞의 값으로 채워 넣는다.</td>
        </tr>
        <tr>
            <td>bfill 또는 backfill</td>
            <td>뒤의 값으로 채워 넣는다.</td>
        </tr>
    </tbody>
</table>

In [51]:
frame = DataFrame(np.arange(9).reshape((3, 3)), index=['a', 'c', 'd'], columns=['Ohio', 'Texas', 'California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [53]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [54]:
states = ['Texas', 'Utah', 'California']

In [55]:
frame.reindex(columns=states)
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [57]:
frame.reindex(index=['a', 'b', 'c', 'd'], method='ffill', columns=states)

Texas  Utah  California
a      1   NaN           2
b      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [58]:
frame.ix[['a', 'b', 'c', 'd'], states]

Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

재색인 함수 인자

<table align="left">
    <thead>
        <td>인자</td>
        <td>설명</td>
    </thead>
    <tbody>
        <tr>
            <td>index</td>
            <td>색인으로 사용할 새로운 순서, Index 인스턴스나 다른 순차적인 자료 구조를 사용할 수 있다.<br/>색인은 복사가 이루어지지 않고 그대로 사용</td>
        </tr>
        <tr>
            <td>method</td>
            <td>보간 메서드</td>
        </tr>
        <tr>
            <td>fill_value</td>
            <td>재색인 과정 중에 새롭게 나타나는 비어있는 데이터를 채우기 위한 값</td>
        </tr>
        <tr>
            <td>limit</td>
            <td>전/후 보간 시 사용하는 최대 갭 크기</td>
        </tr>
        <tr>
            <td>level</td>
            <td>MultiIndex 단계(level)에 단순 색인을 맞춘다. 그렇지 않으면 MultiIndex의 하위 부분집합에 맞춘다.</td>
        </tr>
        <tr>
            <td>copy</td>
            <td>True인 경우 새로운 색인이 이전 색인과 같더라도 데이터를 복사한다. False라면 두 색인이 같을 경우 데이터를 복사하지 않는다.</td>
        </tr>
    </tbody>
</table>

### 5.2.2. 하나의 로우 또는 컬럼 삭제하기

In [61]:
obj = Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [62]:
new_obj = obj.drop('c')

In [63]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [65]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [67]:
data = DataFrame(np.arange(16).reshape((4,4)), 
                 index=['Ohio', 'Colorado', 'Utah', 'New York'], 
                 columns=['one', 'two', 'three', 'four'])

In [68]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [69]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [70]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [71]:
data.drop(['two', 'four'], axis=1)

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

### 5.2.3. 색인하기, 선택하기, 거르기

In [72]:
obj = Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [73]:
obj['b']

1.0

In [75]:
obj[1]

1.0

In [76]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [77]:
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [78]:
obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [79]:
obj[obj<2]

a    0.0
b    1.0
dtype: float64

라벨 이름으로 슬라이싱 하는 것은 시작점과 끝점을 포함한다는 점이 일반 파이썬에서의 슬라이싱과 다른 점이다.

In [80]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [83]:
obj['b':'c'] = 5

In [84]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [85]:
data = DataFrame(np.arange(16).reshape((4, 4)),
                index=['Ohio', 'Colorado', 'Utah', 'New York'],
                columns=['one', 'two', 'three', 'four'])

In [86]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [87]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [88]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [89]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [90]:
data[data['three']>5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [91]:
data<5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [92]:
data[data < 5] = 0

In [93]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [94]:
data.ix['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int64

In [95]:
data.ix[['Colorado', 'Utah'], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [96]:
data.ix[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [97]:
data.ix[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

In [98]:
data.ix[data.three > 5, :3]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

DataFrame의 값 선택하기

<table align="left">
    <thead>
        <td>방식</td>
        <td>설명</td>
    </thead>
    <tbody>
        <tr>
            <td>obj[val]</td>
            <td>DataFrame에서 하나의 컬럼 또는 여러 컬럼을 선택한다. 편의를 위해서 불리언 배열, 슬라이스, 불리언 DataFrame 을 사용할 수 있다.</td>
        </tr>
        <tr>
            <td>obj.ix[val]</td>
            <td>DataFrame에서 로우의 부분집합을 선택한다.</td>
        </tr>
        <tr>
            <td>obj.ix[:, val]</td>
            <td>DataFrame에서 컬럼의 부분집합을 선택한다.</td>
        </tr>
        <tr>
            <td>obj.ix[val1, val2]</td>
            <td>DataFrame에서 로우와 컬럼의 부분집합을 선택한다.</td>
        </tr>
        <tr>
            <td>reindex 메서드</td>
            <td>하나 이상의 축을 새로운 색인으로 맞춘다.</td>
        </tr>
        <tr>
            <td>xs 메서드</td>
            <td>라벨 이름으로 단일 로우나 컬럼을 Series 형식으로 선택한다.</td>
        </tr>
        <tr>
            <td>icol, irow 메서드</td>
            <td>각각 정수 색인으로 단일 로우나 컬럼을 Series 형식으로 선택한다.</td>
        </tr>
        <tr>
            <td>get_value, set_value 메서드</td>
            <td>로우와 컬럼 으림으로 DataFrame 값을 선택한다.</td>
        </tr>
    </tbody>
</table>

### 5.2.4 산술연산과 데이터 정렬

In [100]:
s1 = Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])

In [101]:
s2 = Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])

In [102]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [103]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [104]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [107]:
df1 = DataFrame(np.arange(9.).reshape((3, 3)), 
               columns=list('bcd'),
               index=['Ohio', 'Texas', 'Colorado'])

In [109]:
df2 = DataFrame(np.arange(12.).reshape((4, 3)), 
               columns=list('bde'),
               index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [110]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [111]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [112]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [113]:
df1 = DataFrame(np.arange(12.).reshape((3, 4)), columns=list('abcd'))

In [114]:
df2 = DataFrame(np.arange(20.).reshape((4, 5)), columns=list('abcde'))

In [115]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [116]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [117]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [118]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [119]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

산술연산 메서드

<table align="left">
    <thead>
        <td>메서드</td>
        <td>설명</td>
    </thead>
    <tbody>
        <tr>
            <td>add</td>
            <td>덧셈(+)을 위한 메서드</td>
        </tr>
        <tr>
            <td>sub</td>
            <td>뺄셈(-)을 위한 메서드</td>
        </tr>
        <tr>
            <td>div</td>
            <td>나눗셈(/)을 위한 메서드</td>
        </tr>
        <tr>
            <td>mul</td>
            <td>곱셈(*)을 위한 메서드</td>
        </tr>
    </tbody>
</table>

DataFrame 과 Series 간의 연산

In [120]:
arr = np.arange(12.).reshape((3, 4))

In [121]:
arr

array([[  0.,   1.,   2.,   3.],
       [  4.,   5.,   6.,   7.],
       [  8.,   9.,  10.,  11.]])

In [122]:
arr[0]

array([ 0.,  1.,  2.,  3.])

In [123]:
arr - arr[0]

array([[ 0.,  0.,  0.,  0.],
       [ 4.,  4.,  4.,  4.],
       [ 8.,  8.,  8.,  8.]])

DataFrame 과 Series 의 연산은 브로드캐스트(broadcasting) 에 대한 예제이다.<br/>벡터연산을 쉽게 할 수 있도록 하기 위해 pandas 가 갖고 있는 특징 중 하나이다.

In [124]:
frame = DataFrame(np.arange(12.).reshape((4, 3)),
                 columns=list('bde'),
                 index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [125]:
series = frame.ix[0]

In [126]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [127]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [128]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [130]:
frame.sub(series)

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [131]:
series2 = Series(range(3), index=['b', 'e' , 'f'])

In [133]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [134]:
series3 = frame['d']

In [135]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [136]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [137]:
frame.sub(series3, axis=0)

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

### 5.2.5. 함수 적용과 매핑

pandas 객체에도 NumPy 유니버셜 함수(배열의 각 원소에 적용되는 메서드)를 적용할 수 있다.

In [140]:
frame = DataFrame(np.random.randn(4, 3),
                 columns=list('bde'),
                 index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [141]:
frame

b         d         e
Utah   -1.884544  0.129619  0.420007
Ohio    1.268450  1.043249 -1.180035
Texas   0.229025 -2.055630  0.742132
Oregon -0.311410 -0.241654 -1.740452

In [142]:
np.abs(frame)

b         d         e
Utah    1.884544  0.129619  0.420007
Ohio    1.268450  1.043249  1.180035
Texas   0.229025  2.055630  0.742132
Oregon  0.311410  0.241654  1.740452

In [143]:
f = lambda x : x.max() - x.min()

In [144]:
frame.apply(f)

b    3.152994
d    3.098879
e    2.482584
dtype: float64

In [145]:
frame.apply(f, axis=1)

Utah      2.304551
Ohio      2.448484
Texas     2.797762
Oregon    1.498799
dtype: float64

In [146]:
def f(x):
    return Series([x.min(), x.max()], index=['min', 'max'])

In [147]:
frame.apply(f)

b         d         e
min -1.884544 -2.055630 -1.740452
max  1.268450  1.043249  0.742132

In [148]:
format = lambda x: '%.2f' % x

In [149]:
frame.applymap(format)

b      d      e
Utah    -1.88   0.13   0.42
Ohio     1.27   1.04  -1.18
Texas    0.23  -2.06   0.74
Oregon  -0.31  -0.24  -1.74

In [150]:
frame['e'].map(format)

Utah       0.42
Ohio      -1.18
Texas      0.74
Oregon    -1.74
Name: e, dtype: object

### 5.2.6 정렬과 순위

In [151]:
obj = Series(range(4), index=['d', 'a', 'b', 'c'])

In [153]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [154]:
frame = DataFrame(np.arange(8).reshape((2, 4)), index=['three', 'one'], columns=['d', 'a' ,'b', 'c'])

In [155]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [156]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [157]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [158]:
obj = Series([4, 7, -3, 2])

In [159]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [160]:
obj = Series([4, np.nan, 7, np.nan, -3, 2])

NAN 값은 정렬(sort_values) 시 제일 마지막에 위치한다.

In [163]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [162]:
obj.sort_values(ascending=False)

2    7.0
0    4.0
5    2.0
4   -3.0
1    NaN
3    NaN
dtype: float64

In [164]:
frame = DataFrame({'b':[4, 7, -3, 2], 'a':[0, 1, 0, 1]})

In [165]:
frame

a  b
0  0  4
1  1  7
2  0 -3
3  1  2

In [166]:
frame.sort_values(by='b')

a  b
2  0 -3
3  1  2
0  0  4
1  1  7

In [167]:
frame.sort_values(by=['a', 'b'])

a  b
2  0 -3
0  0  4
3  1  2
1  1  7

순위는 정렬과 거의 흡사하면, 1부터 배열의 유효한 데이터 개수까지의 순위를 매긴다.<br/>또한 numpy.argsort 에서 반환하는 간접 정렬 색인과 유사하나, 동률인 순위를 처리하는 방식이 다르다.

In [168]:
obj = Series([7, -5, 7, 4, 2, 0, 4])

rank() 의 경우 동률이 발생할 경우 평균 순위를 매긴다

In [169]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

데이터 상에서 나타나는 순서에 따라 순위를 매길 수도 있다.

In [170]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

내림차순으로 순위를 매길 수도 있다.

In [171]:
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [172]:
frame = DataFrame({'b':[4.3, 7, -3, 2], 'a':[0, 1, 0, 1], 'c': [-2, 5, 8, -2.5]})

In [173]:
frame

a    b    c
0  0  4.3 -2.0
1  1  7.0  5.0
2  0 -3.0  8.0
3  1  2.0 -2.5

In [174]:
frame.rank(axis=1)

a    b    c
0  2.0  3.0  1.0
1  1.0  3.0  2.0
2  2.0  1.0  3.0
3  2.0  3.0  1.0

순위의 동률을 처리하는 메서드

<table align="left">
    <thead>
        <td>메서드</td>
        <td>설명</td>
    </thead>
    <tbody>
        <tr>
            <td>average</td>
            <td>기본값 : 같은 값을 가지는 항목의 평균 값을 순위로 삼는다.</td>
        </tr>
        <tr>
            <td>min</td>
            <td>같은 값을 가지는 그룹을 낮은 순위로 매긴다.</td>
        </tr>
        <tr>
            <td>max</td>
            <td>같은 값을 가지는 그룹을 높은 순위로 매긴다.</td>
        </tr>
        <tr>
            <td>first</td>
            <td>데이터 내에서 위치에 따라 순위를 매긴다.</td>
        </tr>
    </tbody>
</table>

### 5.2.7. 중복 색인